import {test} from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
import {defaults,validate,activeAnnouncements} from './cms-schema.mjs';
const announcement={id:'a1111111-1111-4111-8111-111111111111',enabled:true,title:'Closed Saturday',message:'Test',button:'Book',link:'https://bookings.obeeapp.com/pockyasianrestaurant',start:'2026-12-01T09:00:00+10:00',end:'2026-12-26T09:00:00+10:00'};
test('content schema keeps defaults and strips layout/code fields',()=>{assert.deepEqual(validate({...defaults,css:'body{}',html:'<script>'}),defaults);});
test('announcement links and schedules reject dangerous or invalid values',()=>{for(const patch of [{link:'javascript:alert(1)'},{link:'http://example.com'},{end:'2026-11-01T09:00:00+10:00'},{enabled:'true'},{start:'invalid'}])assert.throws(()=>validate({...defaults,announcements:[{...announcement,...patch}]}));});
test('announcements start and expire in AEST',()=>{const start=Date.parse(announcement.start),end=Date.parse(announcement.end);assert.equal(activeAnnouncements([announcement],start-1).length,0);assert.equal(activeAnnouncements([announcement],start).length,1);assert.equal(activeAnnouncements([announcement],end).length,0);assert.equal(activeAnnouncements([{...announcement,enabled:false}],start).length,0);});
test('menus must be uploaded menu URLs',()=>{assert.throws(()=>validate({...defaults,menu:'https://evil.example/file.pdf'}));assert.throws(()=>validate({...defaults,menu:'/api/cms?menu=../../secret'}));});
let auth=null,role=[],entry=null,stored=[],writes=0;
const store={get:async()=>null,getWithMetadata:async()=>entry,set:async(k,v)=>{stored.push(k);return{modified:true,etag:'2'};},setJSON:async(k,v,opts)=>{stored.push(k);if(k==='content'){writes++;entry={data:v,etag:'2'};}return{modified:true,etag:'2'};}};
// Replace only infrastructure imports; run the production handler against controlled services.
let source=await readFile('cms-functions/cms.mjs','utf8');source=source.replace("import {getStore} from '@netlify/blobs';",'const getStore=()=>globalThis.cmsTest.store;').replace("import {getUser,admin,verifyRequestOrigin} from '@netlify/identity';",'const getUser=async()=>globalThis.cmsTest.auth(); const admin={getUser:async()=>({roles:globalThis.cmsTest.roles()})};const verifyRequestOrigin=r=>{if(r.headers.get("Origin")!==new URL(r.url).origin){const e=Error("origin");e.status=403;throw e;}};').replace("'../cms-schema.mjs'",JSON.stringify(new URL('./cms-schema.mjs',import.meta.url).href));
globalThis.cmsTest={store,auth:()=>auth,roles:()=>role};const {default:handler}=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
const req=(body,options={})=>new Request('https://pockyasianrestaurant.com.au/api/cms',{method:'PUT',headers:{Origin:'https://pockyasianrestaurant.com.au','Content-Type':'application/json',...options.headers},body:JSON.stringify(body),...options});
test('public read exposes defaults only',async()=>{assert.deepEqual((await(await handler(new Request('https://pockyasianrestaurant.com.au/api/cms'))).json()).content,defaults);});
test('writes require authenticated current editor role and same origin',async()=>{assert.equal((await handler(req({content:defaults,version:null}))).status,401);auth={id:'user'};assert.equal((await handler(req({content:defaults,version:null}))).status,403);role=['content-editor'];assert.equal((await handler(req({content:defaults,version:null},{headers:{Origin:'https://evil.example'}}))).status,403);assert.equal(writes,0);});
test('editor publishing succeeds and stale revisions cannot overwrite',async()=>{assert.equal((await handler(req({content:defaults,version:null}))).status,200);assert.equal(writes,1);assert.equal((await handler(req({content:{...defaults,note:'stale'},version:null}))).status,409);assert.equal(writes,1);});
test('non-PDF uploads rejected and valid PDF stored under immutable key',async()=>{const request=body=>new Request('https://pockyasianrestaurant.com.au/api/cms',{method:'POST',headers:{Origin:'https://pockyasianrestaurant.com.au','Content-Type':'application/pdf'},body});assert.equal((await handler(request('invalid file'))).status,400);const response=await handler(request('%PDF-1.7 test'));assert.equal(response.status,200);assert.match((await response.json()).url,/^\/api\/cms\?menu=[a-f0-9-]{36}$/);});
